  name: Deploy to GitHub Pages
  on:
    push:
      branches:
        - main
  jobs:
    gh-pages-deploy:
      name: Deploying to GH-Pages
      runs-on: ubuntu-latest
      steps:
        - name: Checkout branch
          uses: actions/checkout@v3

        - name: Setup Node.js for use with actions
          uses: actions/setup-node@v3
          with:
            node-version: 16

        - name: Clean install dependencies
          run: npm ci

        - name: Run deploy script
          run: |
            git config user.name GarridoY && git config user.email 33898925+GarridoY@users.noreply.github.com
            npm run gh-pages-deploy
